### ISSUE TITLE
Front label recess

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#108]
The recess for the front panel sticker should be deeper. I measure 0.35 mm for the sticker thickness. Can we do a touch deeper than that?

**Comment by starno** [comment]
How deep do you want to go, 0.5mm?  I'm already concerned this is going to be a problematic area because its already bending the design rules about keeping a nominal thickness and the bezel needs to be a regular shape or it will just be an eyesore.

![capture](https://cloud.githubusercontent.com/assets/352025/9149293/0a1f2aac-3dd6-11e5-8422-b479752bb44f.PNG)

**Comment by charlespax** [comment]
How deep is it now? How do you feel about 0.35 mm or 0.4 mm, so the label is at least flush?

**Comment by starno** [comment]
It was at 0.25mm, I made it 0.4mm because we can always make the depth shallower if problems arrise.

![capture](https://cloud.githubusercontent.com/assets/352025/9149707/bee2061e-3de8-11e5-90c7-7d41554b5320.PNG)
