### ISSUE TITLE
Floppy top panel

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#34]
In the Enclosure version 0.1 (SLA) print the top panel flops around a bit when placed in one side of the enclosure. When the enclosure is fully assembled there is slight movement, but nothing that would cause a problem.

For production it would be good to have the panel be more erect. This would aid in installing the back of the enclosure.

Side view:
![img_20141218_122942](https://cloud.githubusercontent.com/assets/281642/5500338/8555ad0a-877d-11e4-9ee1-20c2c3ef43c8.jpg)

Close up view?
![img_20141218_123015](https://cloud.githubusercontent.com/assets/281642/5500341/94ba1236-877d-11e4-8182-2539ca0b7886.jpg)

Top view:
![img_20141218_123031](https://cloud.githubusercontent.com/assets/281642/5500345/9d093ae8-877d-11e4-9d92-9247c5ed22ff.jpg)

**Comment by starno** [comment]
I tightened up that gap so that there is not much wiggle room even after the drafting.  The wall that supports the underside of the top also got taller and I made the top sit deeper into the groove so that it is wont tip back nearly as much during installation.

![capture](https://cloud.githubusercontent.com/assets/352025/5774027/63409cce-9da4-11e4-9ad3-96ca29d1f573.PNG)
