### ISSUE TITLE
LCD constraint at bottom

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#37]
In the Enclosure version 0.1 (SLA) print there is a large gap between the LCD and enclosure at the bottom. I think these ribs should be extended to constrain the LCD.
![img_20141218_123528](https://cloud.githubusercontent.com/assets/281642/5500448/b1de0190-877f-11e4-948c-f13d262e9527.jpg)

The same gap exists int he model.
![screen shot 2014-12-19 at 13 07 27](https://cloud.githubusercontent.com/assets/281642/5500473/047ec3a8-8780-11e4-95f1-b48ab7b9c357.png)

**Comment by starno** [comment]
I closed up the gap as far as I could, because the fillets on the bottom of the ribs would interfere.  I also just noticed the logo detent is a thin section so we might have to shift everything back to compensate

![capture](https://cloud.githubusercontent.com/assets/352025/5776202/11c05dba-9dbf-11e4-9aa8-b87b4888c209.PNG)

**Comment by charlespax** [comment]
This should be fully addressed for Enclosure version 0.2 (SLA).

Do we need drafting on that edge? We should be able to get away with small sections not being drafted.

Does that corner need to be filleted?

**Comment by starno** [comment]
Fillet removed and the gap is closed in (Now 0.14mm from LCD)  Should be nice and snug

![bottom-clearance](https://cloud.githubusercontent.com/assets/352025/5895984/20a6f068-a568-11e4-893c-82feb068c01a.PNG)

**Comment by charlespax** [comment]
Mmm... looks very cozy.
