### ISSUE TITLE
Enclosure gap

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#41]
In the Enclosure version 0.1 (SLA) print there seems to be a bit of a gap between the two enclosure halves. There is a gap modeled in. Is there a technical reason for this? Right now the enclosure feels a bit janky.

I believe when the enclosure experiences torsion the stress will be transferred to the screws and threaded inserts because the two halves of the enclosure are not fully engaged with each other.

When I push the two halves in different directions, this is the maximum gap:
![img_20141218_125054](https://cloud.githubusercontent.com/assets/281642/5500573/25dd9b44-8782-11e4-9366-a43e159e7cdc.jpg)

The model:
![screen shot 2014-12-19 at 13 23 59](https://cloud.githubusercontent.com/assets/281642/5500577/58990190-8782-11e4-8e2e-3159fabb7f69.png)

![img_20141218_125011](https://cloud.githubusercontent.com/assets/281642/5500674/b04aaf0e-8784-11e4-9b17-3d90728a0dad.jpg)

**Comment by starno** [comment]
The space between the two is 0.14mm down from 0.27mm.  I also changed the vertical spacing between them so that they dont bottom out anymore.   Since we originally intended the PCB to be pinched between the front and back, the bosses on the front and back are now the only points that contact.

![capture](https://cloud.githubusercontent.com/assets/352025/5776950/03d657a4-9dc9-11e4-939d-fb7c38087525.PNG)
