### ISSUE TITLE
Window chamfer

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#58]
We have mild chamfer on the window. I had this in the original prototoype. Looking at the Enclosure version 0.1 (SLA) print, it doesn't seem to have an aesthetic point to it. Maybe we should have just a normal small 45 degree chamfer. This may go better with an injection molded window (https://github.com/PaxInstruments/t400-enclosure/issues/57) and give us a little more height to the branding area (https://github.com/PaxInstruments/t400-enclosure/issues/15).

![screen shot 2014-12-27 at 00 37 00](https://cloud.githubusercontent.com/assets/281642/5558387/8aa7dd44-8d60-11e4-9a3a-93c33717da2a.png)
![img_20141227_003828](https://cloud.githubusercontent.com/assets/281642/5558394/d880a6e0-8d60-11e4-94dd-26f19c2b40e5.jpg)

**Comment by starno** [comment]
So the buttons are pretty much fixed in place because of the wall between them and the PCB.  The overlap of the window chamfer on the LCD is also fixed because it covers up blank real estate on the screen.  So changing that chamfer to be 45deg will make the buttons look off-center.  are you sure that is worth it?

![capture](https://cloud.githubusercontent.com/assets/352025/5849894/e05f4bac-a226-11e4-8985-d80fd2dd980b.PNG)

**Comment by charlespax** [comment]
Getting some real estate for a molded-in logo _would_ be pretty sweet. The angle right now is so subtle that on the 3D print I really can't tell it's there.

We already have an SLA print of the current style. Maybe we should try changing the window chamfer and adding a molded-in logo for the next SLA print. Then we can compare the two physical prints. What do you think?

**Comment by starno** [comment]
This was addressed in 3fe82aabea16d16189edf99ddfce018d29256202.  The chamfer is a sharper angle and adds more real estate. 
![chamfer](https://cloud.githubusercontent.com/assets/352025/5855982/9b4bf21a-a279-11e4-8b89-f703aceebefd.PNG)

Ill need the vector art to add in the logo mentioned in issue #59
