### ISSUE TITLE
Battery cover clearance

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#74]
The battery cover is tight. We should increase the clearance at the top or have the top drafted more. Probably a combination of both.

**Comment by starno** [comment]
This was fixed in commit 1d5f205a0f910df804bc58a5ef8371cb79da2760

The draft increased to 4 degrees.  Here is the comparison of gained clearance when inserting battery cover into back

![capture](https://cloud.githubusercontent.com/assets/352025/5995897/72ed64c2-aad8-11e4-9afc-43198b27ffdd.PNG)

![capture2](https://cloud.githubusercontent.com/assets/352025/5995899/75d10996-aad8-11e4-972e-fe0142e49b34.PNG)
