### ISSUE TITLE
Buttons dont click

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#78]
Not sure what's going on, but the buttons aren't clicking in Enclosure version 0.2 (SLA).

**Comment by starno** [comment]
The button height dimensions given in #62 were 0.1mm off from what I measured on the prototype.  Since the keypad indents were modeled line to line sitting on top of the buttons, a tightly fastened enclosure could depress the buttons making them un-clickable.  

I added the extra height to the modeled buttons, and added a 0.25mm clearance to avoid pinching in the future.

![capture](https://cloud.githubusercontent.com/assets/352025/5991103/a860b846-aa12-11e4-8e73-ec2047900604.PNG)
