### ISSUE TITLE
Enclosure for 3D printing

### ISSUE THREAD

**Issue by cibomahto** [PaxInstruments/t400-enclosure#82]
It would be awesome if there were STL files available for 3d printing a case based on the injection mold design. The solidworks parts are awesome but pretty huge to download over slow internet.

**Comment by charlespax** [comment]
There are older set of  Solidworks and STL files for 3D printing in https://github.com/PaxInstruments/t400-enclosure/tree/master/3D%20Printed. After we go into production, we should update or redesign 3D printable files.

**Comment by charlespax** [comment]
@starno has been having pretty good success with FDM 3D prints. The only significant problems is the bridging involved with the battery compartment.

**Comment by cibomahto** [comment]
Yeah, no rush here- sometime after everything is finalized is probably soon enough :-).

**Comment by charlespax** [comment]
We'l get to this at some point. Putting in ice box.

**Comment by starno** [comment]
I've kept STLs out of the repo during development because the design is changing a lot and they quickly become useless, making the repo even larger.  As of now the only thing that has trouble with FDM are the small features on the bail.  Those features are going to be getting larger and if the production units are not easily printed, I can make a printable version.

**Comment by charlespax** [comment]
At this point I don't think we need to commit to doing anything special. Let's see how the final design works for printing. Moving to ice box.

**Comment by charlespax** [comment]
3D printing technology is good enough that people can order SLA prints of the actual enclosure. If we make another one that is good for 3D printing, I would consider it a separate product. Closing issue.
