### ISSUE TITLE
Top panel holes

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#88]
We are developing a custom thermocouple connector (https://github.com/PaxInstruments/t400-electronics/issues/17). We may have to move the connector holes on the top panel to match. There is a 3D model in the electronics repository (https://github.com/PaxInstruments/t400-electronics/tree/master/solidworks/clip).

The enclosure 3D model should be updated with the connector model.

Current design:
![unnamed_qq_screenshot20150305043544](https://cloud.githubusercontent.com/assets/281642/6723088/9cc6ab2e-ce1d-11e4-9229-67de86d3d02b.png)

**Comment by starno** [comment]
I like this because it moves the holes in the top closer to true center.  I updated the PCBA to have these populated, but I left them in the same locations as the previous connectors.  

![capture4](https://cloud.githubusercontent.com/assets/352025/6745450/fa8ae26e-cef1-11e4-85d3-ceb32f224d35.PNG)
resulting top panel:
![capture3](https://cloud.githubusercontent.com/assets/352025/6745454/04f34fe8-cef2-11e4-8c8b-a6de4bdaa11f.PNG)

@charlespax do you want smaller number indicators now?
@samchoy88 do you have coordinates of each thermocouple connector for me so I can match the PCBA in CAD to match the latest board files?

**Comment by charlespax** [comment]
I don't have the coordinates for the connectors. Once the connector design is approved and we cut a PO, we will have an accurate model. The connector is still in the design phase.

**Comment by charlespax** [comment]
The number can probably be a touch smaller, but I think it looks fine this way too. Let's get a prototype of this design and see how we feel about it.

**Comment by charlespax** [comment]
The most recent prototype looked great. Closing issue.
