### ISSUE TITLE
Peg slot chamfer

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#89]
Should this be chamfered more?

![screen shot 2015-03-19 at 20 05 47](https://cloud.githubusercontent.com/assets/281642/6730039/5fbb6c96-ce73-11e4-9d9c-fbe8684e41ae.png)

**Comment by starno** [comment]
Yeah, thats a good idea since the snap is stronger now.  The image above is 0.25mm flare at 0.75mm distance.  That seemed to work well with the encl-0.3 bail.  I just opened it to 0.4mm flare at 0.75mm distance.

![capture4](https://cloud.githubusercontent.com/assets/352025/6745102/496b9b26-ceed-11e4-8978-5fdbf2de5310.PNG)
