### ISSUE TITLE
SD card insertion

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-enclosure#96]
The SD card can be lost int he device if it is inserted at an angle.
![img_20150324_203725](https://cloud.githubusercontent.com/assets/281642/6819532/59e4e61a-d2fd-11e4-81b9-32d31362901d.jpg)
![img_20150324_203805](https://cloud.githubusercontent.com/assets/281642/6819533/59f8575e-d2fd-11e4-935f-f11672c6ab58.jpg)

We should be able to solve this by adding ribs where I marked the black lines.
![img_20150325_144521](https://cloud.githubusercontent.com/assets/281642/6819566/e1f92002-d2fd-11e4-8257-bc929242249a.jpg)

**Comment by starno** [comment]
I extended existing ribs on the front and back panels so that the clearance is smaller than the SD card
![capture](https://cloud.githubusercontent.com/assets/352025/6884401/aeffb1d4-d622-11e4-887d-cd132e52ff80.PNG)
![capture2](https://cloud.githubusercontent.com/assets/352025/6884402/b45dcff8-d622-11e4-9334-2f19d04a8846.PNG)
